services:
  db:
    image: mysql:9.2
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/docker/mysql/init:/docker-entrypoint-initdb.d


  service-auth:
    build: ./backend/services/service-auth
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - .env


  service-girls:
    build: ./backend/services/service-girls
    ports:
      - "3002:3002"
    volumes:
      - ./backend/static:/app/static
    depends_on:
      - db
    env_file:
      - .env


  service-users:
    build: ./backend/services/service-users
    ports:
      - "3003:3003"
    depends_on:
      - db
    env_file:
      - .env


  service-gateway:
    build: ./backend/service-gateway
    ports:
      - "3000:3000"
    volumes:
    - ./backend/static:/app/static 
    depends_on:
      - service-auth
      - service-users
      - service-girls

  frontend-host:
    build:
      context: .
      dockerfile: apps/host/Dockerfile
      args:
        REMOTE_MAIN_URL: http://localhost:3004
        REMOTE_ADMIN_URL: http://localhost:3005
    container_name: fwa_frontend_host
    ports:
      - "80:80"
    depends_on:
      - service-gateway

  frontend-remote-main:
    build:
      context: .
      dockerfile: apps/remote-main/Dockerfile
    container_name: fwa_frontend_remote_main
    ports:
      - "3004:80"
    depends_on:
      - service-gateway

  frontend-remote-admin:
    build:
      context: .
      dockerfile: apps/remote-admin/Dockerfile
    container_name: fwa_frontend_remote_admin
    ports:
      - "3005:80"
    depends_on:
      - service-gateway

volumes:
  mysql_data:
