# FROM nginx:alpine
#
# RUN rm /etc/nginx/conf.d/default.conf
#
# COPY nginx.conf /etc/nginx/conf.d
#
# RUN mkdir -p /usr/share/nginx/html/videos
# COPY ./static/videos/*.* /usr/share/nginx/html/videos/
#
# EXPOSE 80
#
# CMD ["nginx", "-g", "daemon off;"]
