version: "3.9"

services:

  service-auth:
    build: ./services/service-auth/
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - ../.env
    volumes:
      - ./services/service-auth:/usr/src/app
      - /usr/src/app/node_modules

  # service-girls:
  #   build: ./services/service-girls/
  #   ports:
  #     - "3002:3002"
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env

  db:
    image: mysql:9.2
    restart: always
    env_file:
      - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
